### ISSUE TITLE
Esforço geral para melhorar a lib

### ISSUE THREAD

**Issue by xthiago** [mrprompt/Cielo#19]
Pessoal, estou abrindo essa issue para discutirmos o que podemos fazer para melhorar o projeto e definir um plano de ação factível. Sei que o @mrprompt começou a fazer várias coisas no branch 3.0-dev, como a inclusão de testes unitários.

Vocês vêem a necessidade de alguma mudança estrutural?

Além dos testes unitários, precisamos também documentar melhor a biblioteca. Também acho que passar a utilizar Guzzle 5 vêem bem a calhar.

Qual será a versão minima do PHP para 3.0-dev?

**Comment by lcobucci** [comment]
Now we're talking!

O Guzzle 5 depende do PHP 5.4 (na real o 4 já depende :P), então acredito que podemos colocar esta versão (se dependesse só de mim diria PHP 5.6, mas seria meio FDP hahahha).

Eu coloco o problema de SSL que tá rolando na #16 e #18 como algo a ser pensado e resolvido pela lib.

Outra coisa que acho que merece um tratamento mais legal é o retorno, a lib poderia (deveria :p) abstrair a forma de comunicação totalmente (ao invés de retornar o XML).

**Comment by straube** [comment]
Eu também sou muito a favor do tratamento do retorno (XML).

Sobre a documentação, não sei se você está falando a nível de código especificamente, @xthiago, mas eu acho que a Wiki aqui no GitHub poderia fazer parte desse esforço. Eu tenho o costume de olhar a Wiki atrás de mais informações em outros projetos e creio que muita gente tem o mesmo hábito.

Outra sugestão: tem alguns tratamentos de parâmetros que poderiam ser feitos internamente. Um exemplo disso é o método `Transacao::setCapturar()`, ele espera uma `string` com `'true'` ou `'false'`, quase passei um `boolean` pra ele esses dias. Nesse caso, podemos manter a possibilidade da `string` para manter retro-compatibilidade, mas também aceitar `boolean`. Devem haver outros casos assim.

**Comment by xthiago** [comment]
Também concordo com o tratamento do retorno. Acredito que deveríamos retornar objetos. Os tratamentos de parâmetros também são muito úteis.

Vocês acham que seria excessivo incluir uma camada para abstrair a transformação objeto/xml (serialização) e outra para comunicação? Isso permitiria que as pessoas criassem suas próprias implementações.

Também tem uma biblioteca maneira chamada JMS Serializer para serialização de objetos. O que pensam?

**Comment by mrprompt** [comment]
A minha idéia no branch 3.0 é transformar tudo em objeto, e tudo 100% testado.
A necessidade do XML só diz respeito a Cielo, então isso não nos importa - a aplicação não precisa saber como a biblioteca envia/recebe os dados, ela deve receber e enviar sempre objetos. Sendo assim, concordo com o @xthiago sobre a camada de abstração.

**Comment by straube** [comment]
Não sei se vocês viram que a Cielo criou alguns repositórios no GitHub há alguns meses atrás. Parece que um dos primeiros commits é de Abril. Descobri por acaso hoje: https://github.com/DeveloperCielo.

Inclusive agora eles têm uma biblioteca PHP oficial: https://github.com/DeveloperCielo/Webservice-1.5-php

Já testaram? Se eles forem abertos a contribuições, acham que vale a pena unir esforços lá?

**Comment by mrprompt** [comment]
@straube vi sim, os caras estão vindo com tudo (finalmente), disponibilizando bibliotecas para diversas linguagens e tudo mais. Um excelente trabalho diga-se de passagem.

**Comment by mrprompt** [comment]
to reabrindo essa issue pq to brincando a um tempo no branch develop, substituindo o curl pelo guzzle e trabalhando integralmente com objetos para as respostas.

**Comment by mrprompt** [comment]
Como a intenção da biblioteca é sempre utilizar as melhoras práticas da linguagem, atualizei a mesma para o PHP7 para trabalharmos melhoras tipagens dos dados.

Como conversado, pretendo eliminar os métodos de XML e trabalharmos apenas com objetos no retorno. 

Os parâmetros também estão sendo transformados em objetos, como Idioma e Ambiente.

Estou tentando mudar o mínimo possível a estrutura, que gosto bastante por sinal.

Estou eliminando também o problemático Curl, deixando tudo a cargo do HTTP Client passado na criação do objeto (padrão é o Guzzle claro).
