### ISSUE TITLE
Compatibilidade com PHP < 5.5+ quebrada

### ISSUE THREAD

**Issue by mrprompt** [mrprompt/Cielo#20]
Após o incremento dos testes unitários, a compatibilidade com o PHP em versões anteriores a 5.5 foi quebrada.

**Comment by xthiago** [comment]
Sugiro atualizar o `README.md` e informar que a branch `2.1-dev` suporta PHP 5.3 e `master` não. :)

**Comment by mrprompt** [comment]
show, valeu

**Comment by mrprompt** [comment]
Atualizei o README informando que a partir de agora, a develop precisa de pelo menos PHP 5.6, e estou atualizando mais coisas ainda.
