### ISSUE TITLE
Retornar o tipo de cancelamento

### ISSUE THREAD

**Issue by gildonei** [mrprompt/Cielo#24]
Implementar método para retornar o tipo de cancelamento (parcial ou total)

**Comment by mrprompt** [comment]
Segundo a documentação:

O cancelamento total, quando realizado com sucesso, altera o status da transação para “9 – Cancelada”, enquanto que o parcial não altera o status da transação, mantendo-a como “6 – Capturada”.

Sendo assim, não há o que implementar, basta checar o status da transação.
