### ISSUE TITLE
Validar valor e validade do cancelamento parcial

### ISSUE THREAD

**Issue by gildonei** [mrprompt/Cielo#25]
Regras do manual do desenvolvedor - ver. 2.5.3

- O cancelamento total é válido tanto para transações capturadas, como autorizadas; o parcial é válido apenas para as capturadas.
- O prazo de cancelamento é de até 120 dias para a modalidade crédito e D+0 para débito.
- O cancelamento total, quando realizado com sucesso, altera o status da transação para “9 – Cancelada”, enquanto que o parcial não altera o status da transação, mantendo-a como “6 – Capturada”.
- Caso a TAG <valor> não seja fornecida, o sistema assumirá um cancelamento total.
- Para bandeira AMEX está disponível apenas o cancelamento total.
- Para a modalidade débito, não existe a possibilidade de efetuar cancelamento parcial

**Comment by mrprompt** [comment]
Precisamos checar se a versão que da api que a lib consome aceita essa funcionalidade descrita no manual. Ou atualizarmos a lib para consumir a versão mais atual do serviço.
